name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: lee7198/client-web
          stage: main
          yaml: >
            name: goormthon

            app: web

            options:
              nodeversion: "16"
              spa: true
              npmrc: |-
                @goorm-dev:registry=https://npm.pkg.github.com/
                //npm.pkg.github.com/:_authToken=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
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
